### ISSUE TITLE
Cannot open URL including space via Process.Start of C#

### ISSUE THREAD

**Issue by HashidaTKS** [ThinBridge/ThinBridge#40]
### Describe the bug

既定のWebアプリにThinBridgeを指定した状態で、以下のようにC#の`Process.Start()`で、引数に空白を含むURLを指定した場合、指定したURLが開けない。

```
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Process.Start("https://example.com?arg=1, 2");
        }
    }
}
```

### To Reproduce

* ThinBridgeをインストールする
* Windowsの設定->既定のアプリ->Webから、ThinBridgeを既定のアプリに指定する
* 上記のC#アプリケーションを作成実行する。

### Expected behavior

指定したURLが表示される。

### Your Environment

```markdown
- ThinBridge version:4.0.2.6
```

### Your Configuration

```ini
Default
```

### Your TRACE log (IE)

```shell
RedirectorEXE	2023-06-08 18:03:15	ThinBridgeBHO.ini [C:\Program Files\ThinBridge\ThinBridgeBHO.ini]
RedirectorEXE	2023-06-08 18:03:15	InitInstance Stage:01
RedirectorEXE	2023-06-08 18:03:15	InitInstance Stage:02
```

### Additional context

`Process.Start()`を呼びだす側で適切にエスケープすれば回避可能。

```
var escapedUrl = Uri.EscapeUriString("https://example.com/?arg=1, 2");
System.Diagnostics.Process.Start(escapedUrl);
```

ただ、使用感としてはエスケープなしで使えた方が良いのではないか？

修正方針としては、現時点では以下の方法を思いついている。

https://github.com/ThinBridge/ThinBridge/blob/master/ThinBridgeX64.iss#L84

といった、セットアップで

`"""{app}\TBRedirector.exe"" %1"`

を指定している箇所を、

`"""{app}\TBRedirector.exe"" ""%1"""`

のように修正する。

サンプルプログラムでは、`%1`には`https://example.com?arg=1, 2`が渡ってきている。
そのため、修正前では

`"{app}\TBRedirector.exe" https://example.com?arg=1, 2`

となっている。
これは、空白が含まれるので、`https://example.com?arg=1,`が第一引数、`2`が第二引数と判断される。

修正後では

`"{app}\TBRedirector.exe" "https://example.com?arg=1, 2"`

となるので、`https://example.com?arg=1, 2`という一つの引数とみなされる。
呼び出し側が元々第一引数として渡したものが、正しく第一引数としてわたることになるので、上述の回避策のように、ユーザーが事前にエスケープするかどうかに関わらず、正しい姿になっているような気がする。
懸念点は、既存のユーザーがこのことに気付いて`"`で括るようにしていたケースで、`""https://example.com?arg=1, 2""`のようになってしまわないかという点。

**Comment by HashidaTKS** [comment]
仮に `""https://example.com?arg=1, 2""` となったとき、引数解析に `""https://example.com?arg=1,`と`2""`という二つの引数とみなされてしまう。
なので、ThinBridge側（TBRedirector側）で余分なダブルクォートを外すという処理ができない。

**Comment by ashie** [comment]
あんまりよく考えてないんですが、個人的にはレジストリ設定でクォートするだけで十分じゃないかなという気がしてます。

**Comment by HashidaTKS** [comment]
ありがとうございます。
そうですね、私も以下の理由から単にクォートするだけで十分ではないかと思い始めていました。

* すぐに `"""{app}\TBRedirector.exe"" %1"` の `%1` にダブルクォート付きを渡す方法が分からない
* 仮にスペース入りで動かないと気付いたユーザーがいても、上記の事情から、URLのエスケープを試すのではないか

**Comment by piroor** [comment]
クォーテーションが二重になっている例のあたりから混乱してきました……

**Comment by HashidaTKS** [comment]
@piroor さんの疑問の混乱の助けになるのか分からないですが

* [セットアップ](https://github.com/ThinBridge/ThinBridge/blob/master/ThinBridgeX64.iss#L84) の記述を `"""{app}\TBRedirector.exe"" ""%1"""` と変更すると、コマンドプロンプトでは`"{app}\TBRedirector.exe" "%1"`を実行しようとする。
* もし `%1` が `"hoge foo"`という文字列だったとしたら、 `"{app}\TBRedirector.exe" ""hoge foo""` となる
* これは、TBRedirectorとしては、第一引数`""hoge`、第二引数`foo""`が渡ってきたと思ってしまう。
* もしこれをTBRedirector側で対応するとすると、複数の引数を一つにマージするような処理が必要になるが、あまりやりたくない。
* なので、やるとしたらレジストリの値の方で頑張りたい。
* ただ、 `%1` に `"hoge foo"` というようなダブルクォートで括られた文字列を渡す方法がすぐに分からないこともあり、この懸念は考えすぎではないか？（単に `"""{app}\TBRedirector.exe"" ""%1"""` と変更するだけで大丈夫ではないか？）

という流れのつもりでいました。

**Comment by HashidaTKS** [comment]
修正のPRがマージ済み。
