### ISSUE TITLE
Microsoft Edgeアドオンを審査に投稿する

### ISSUE THREAD

**Issue by fujimotos** [ThinBridge/ThinBridge#5]
リソース制限機能を追加したEdge版アドオンを審査に投稿します。

**必要なタスク**

- [x] ThinBridge公開版の新しいバージョンをリリースする
- [x] Edgeアドオンページの説明を更新する。
- [x] Microsoftのパートナーセンターから新しいアドオンの審査を依頼する。

**ThinBridgeのリリースについて**

  * Edgeアドオンの審査の中で「実際にアドオンが使えるか？」がチェックされるため必要。
    * 一般のEdgeの利用者が、所定の手順に沿って使えることが求められる。
    * 審査基準の詳細については [Edgeアドオンストア開発者ポリシー](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies) を参照。
    * （実際に審査者が試しているようで、過去に案内が不十分という理由で弾かれた事あり）
  * `ThinBridge v4.0.2.4`として https://github.com/ThinBridge/ThinBridge/releases で公開します。

**Comment by fujimotos** [comment]
https://github.com/ThinBridge/ThinBridge/tree/release-v4024

リリース準備はこの`release-v4024`ブランチで進めています。

* 今回公開するThinBridgeインストーラが日本語のみサポートなので、このタイミングでプロジェクト内の手順案内も日本語に統一してます。
* これで審査要件の [「1.7 ローカリゼーション」](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies#17-localization) を満たすことを期待してます。

**Comment by fujimotos** [comment]
リリースの前準備が一通り手元で整いました。

後は今回実装したリソース制限機能について「これでOK」というGOサインが出れば、
このままGitHubでの公開版リリース→アドオンの投稿まで進める状態です。

**Comment by tunemicky** [comment]
対応ありがとうございます。
「これでOK」！！Goお願いします。

**Comment by fujimotos** [comment]
@tunemicky ありがとうございます！週明け月曜に投稿させていただきます。

**Comment by fujimotos** [comment]
ThinBridge v4.0.2.4 をGitHub上でリリースしました。

https://github.com/ThinBridge/ThinBridge/releases/tag/v4.0.2.4

このリリースにはThinBridgeのサイドバーからアクセスできるようになっています：

![20211108-thinbridge](https://user-images.githubusercontent.com/8974561/140677232-c9cdf69f-83ca-42b5-902f-1b26cb98e3ed.png)

**Comment by fujimotos** [comment]
アドオンをMicrosoftの審査に投稿しました。審査から応答があり次第、随時こちらで共有いたします。

![20211108-1657](https://user-images.githubusercontent.com/8974561/140704403-d1cc1f62-7f56-4422-9452-868b07f2abdd.png)

**Comment by fujimotos** [comment]
@tunemicky アドオンをMicrosoftの審査に投稿しました。現在は審査中のステータスです。

Microsoftから応答があり次第、随時こちらで共有いたします。

![20211108-1657](https://user-images.githubusercontent.com/8974561/140704403-d1cc1f62-7f56-4422-9452-868b07f2abdd.png)

**Comment by fujimotos** [comment]
@tunemicky Microsoftから審査通過の連絡がありました（今回は2日で終わりました）
既に`v1.4.0`として公開されています：

https://microsoftedge.microsoft.com/addons/detail/thinbridge/famoofbkcpjdkihdngnhgbdfkfenhcnf

**Comment by fujimotos** [comment]
公開まで完了したのでクローズします。
